### ISSUE TITLE
Error running phylo-markers

### ISSUE THREAD

**Issue by jtamames** [snayfach/MAGpurify#19]
Dear developers:
I have found the following error when running the phylo-markers options. It happens for some MAGs, not for others. Any help will be appreciated.
Best,

 ```
magpurify phylo-markers results/DAS/H4_DASTool_bins/maxbin.097.fasta.contigs.fa temp/purify

• Calling genes with Prodigal
  all genes: temp/purify/phylo-markers/genes.[ffn|faa]
• Identifying PhyEco phylogenetic marker genes with HMMER
  hmm results: temp/purify/phylo-markers/phyeco.hmmsearch
  marker genes: temp/purify/phylo-markers/markers
• Performing pairwise BLAST alignment of marker genes against database
  blast results: temp/purify/phylo-markers/alns
• Finding taxonomic outliers
Traceback (most recent call last):
  File "/home/tamames/software/miniconda3/bin/magpurify", line 10, in <module>
    sys.exit(cli())
  File "/home/tamames/software/miniconda3/lib/python3.8/site-packages/magpurify/cli.py", line 116, in cli
    args["func"](args)
  File "/home/tamames/software/miniconda3/lib/python3.8/site-packages/magpurify/modules/phylo.py", line 419, in main
    flagged = flag_contigs(args["db"], args["tmp_dir"], args)
  File "/home/tamames/software/miniconda3/lib/python3.8/site-packages/magpurify/modules/phylo.py", line 372, in flag_contigs
    bin.genes[aln["qname"]].annotations.append(annotation)
KeyError: 'megahit_65877_14'

```

**Comment by ShevchenkoAlla** [comment]
> Dear developers: I have found the following error when running the phylo-markers options. It happens for some MAGs, not for others. Any help will be appreciated. Best,
> 
> ```
> magpurify phylo-markers results/DAS/H4_DASTool_bins/maxbin.097.fasta.contigs.fa temp/purify
> 
> • Calling genes with Prodigal
>  all genes: temp/purify/phylo-markers/genes.[ffn|faa]
> • Identifying PhyEco phylogenetic marker genes with HMMER
>  hmm results: temp/purify/phylo-markers/phyeco.hmmsearch
>  marker genes: temp/purify/phylo-markers/markers
> • Performing pairwise BLAST alignment of marker genes against database
>  blast results: temp/purify/phylo-markers/alns
> • Finding taxonomic outliers
> Traceback (most recent call last):
>  File "/home/tamames/software/miniconda3/bin/magpurify", line 10, in <module>
>    sys.exit(cli())
>  File "/home/tamames/software/miniconda3/lib/python3.8/site-packages/magpurify/cli.py", line 116, in cli
>    args["func"](args)
>  File "/home/tamames/software/miniconda3/lib/python3.8/site-packages/magpurify/modules/phylo.py", line 419, in main
>    flagged = flag_contigs(args["db"], args["tmp_dir"], args)
>  File "/home/tamames/software/miniconda3/lib/python3.8/site-packages/magpurify/modules/phylo.py", line 372, in flag_contigs
>    bin.genes[aln["qname"]].annotations.append(annotation)
> KeyError: 'megahit_65877_14'
> ```

Hello,
Have you found a solution?
Thanks,
Best,
Alla
