### ISSUE TITLE
No module named 'utility'

### ISSUE THREAD

**Issue by SilasK** [snayfach/MAGpurify#7]
Traceback (most recent call last):
  File "/home/kiesers/scratch/Test_magpurify/MAGpurify/run_qc.py", line 39, in <module>
    from magpurify import csmg
  File "/home/kiesers/scratch/Test_magpurify/MAGpurify/magpurify/csmg.py", line 4, in <module>
    import utility
ModuleNotFoundError: No module named 'utility'

**Comment by jlli6t** [comment]
Hi @SilasK , are you using python3, have you tried switch to python2, it should works then
